import Header from '@/components/Header';
import Link from 'next/link';
import PaymentPanel from '@/components/PaymentPanel';
import DownloadButton from '@/components/DownloadButton';
import { educationBundles, educationProducts, getEducationProduct } from '@/lib/education';

export default function EducationProductPage({params}:{params:{slug:string}}){
 const product=getEducationProduct(params.slug); const bundle=educationBundles.find(b=>b.slug===params.slug);
 if(bundle){return <><Header/><main><section className="educationProductHero"><Link href="/education" className="back"><span className="arrowIcon">←</span> Все материалы</Link><div className="eyebrow">READY SET / RE:PROJECT EDUCATION</div><h1>{bundle.title}</h1><p>{bundle.description}</p><div className="detailPrice"><small>СТОИМОСТЬ</small><strong>{bundle.price}</strong></div></section><section className="educationProductBody"><div className="sectionTag">01 / INCLUDED</div><div><div className="eyebrow">СОСТАВ НАБОРА</div><h2>Всё<br/><em>внутри.</em></h2><div className="includedList">{bundle.included.map(id=>{const p=educationProducts.find(x=>x.slug===id);return p?<Link href={`/education/${p.slug}`} key={id}><span>{p.num} / {p.category}</span><b>{p.title}</b><i><span className="arrowIcon"></span></i></Link>:null})}</div><div className="educationPurchase"><PaymentPanel amount={Number(bundle.price.replace(/\D/g,''))} description={`re:project education — ${bundle.title}`} productType="education" productSlug={bundle.slug}/></div><div className="materialDownloads"><small>ПОСЛЕ ОПЛАТЫ</small><p>Файлы доступны из личного кабинета и защищены проверкой покупки.</p>{bundle.included.map(id=>{const p=educationProducts.find(x=>x.slug===id);return p?p.files.map(file=><DownloadButton key={file} product={bundle.slug} file={file}/>):null})}</div></div></section></main></>}
 if(!product)return <><Header/><main className="notFound"><h1>Материал не найден.</h1><Link href="/education" className="dark">Вернуться к материалам</Link></main></>;
 return <><Header/><main><section className="educationProductHero"><Link href="/education" className="back"><span className="arrowIcon">←</span> Все материалы</Link><div className="eyebrow">{product.num} / {product.category}</div><h1>{product.title}</h1><p>{product.description}</p><div className="detailPrice"><small>СТОИМОСТЬ</small><strong>{product.price}</strong></div><div className="educationProductMeta"><span>{product.format}</span><span>САМОСТОЯТЕЛЬНОЕ ИСПОЛЬЗОВАНИЕ</span><span>БЕЗ УРОКОВ</span></div><div className="educationOutcome"><small>ЧТО ВЫ ПОЛУЧИТЕ ПОСЛЕ ИЗМЕНЕНИЙ</small><p>{product.outcome}</p></div></section><section className="educationProductBody"><div className="sectionTag">01 / CONTENT</div><div><div className="eyebrow">ЧТО ВНУТРИ</div><h2>Готовый<br/><em>рабочий набор.</em></h2><div className="materialPreview"><div><b>Чеклисты</b><span>контрольные точки, которые можно пройти самостоятельно</span></div><div><b>Шаблоны</b><span>структуры документов и сообщений для копирования и адаптации</span></div><div><b>Таблицы</b><span>готовые поля и статусы для ведения проекта</span></div><div><b>Сценарии</b><span>пошаговая логика работы без привязки к автору материалов</span></div></div><div className="educationPurchase"><PaymentPanel amount={Number(product.price.replace(/\D/g,''))} description={`re:project education — ${product.title}`} productType="education" productSlug={product.slug}/></div><div className="materialDownloads"><small>ПОСЛЕ ОПЛАТЫ</small><p>Файлы доступны из личного кабинета и защищены проверкой покупки.</p>{product.files.map(file=><DownloadButton key={file} product={product.slug} file={file}/>)}</div></div></section></main></>
}
