'use client';
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';import Link from 'next/link';import {getSupabaseBrowser} from '@/lib/supabase-browser';
import PaymentPanel from '@/components/PaymentPanel';
import DownloadButton from '@/components/DownloadButton';
import {getEducationOffer} from '@/lib/education';

type AccountData={user:{id:string;email?:string};role:string;requests:any[];visualizations:any[];payments:any[];messages:any[];educationAccess:any[]};
export default function Account(){const [data,setData]=useState<AccountData|null>(null);const [tab,setTab]=useState('projects');const [error,setError]=useState('');const router=useRouter(); const [chatText,setChatText]=useState(''); const [chatProjectId,setChatProjectId]=useState(''); const [chatError,setChatError]=useState(''); const [chatSending,setChatSending]=useState(false);
 useEffect(()=>{(async()=>{try{const supabase=getSupabaseBrowser();const {data:auth}=await supabase.auth.getUser();if(!auth.user){router.replace('/login');return;}const {data:session}=await supabase.auth.getSession();const response=await fetch('/api/account',{headers:{Authorization:`Bearer ${session.session?.access_token||''}`}});const json=await response.json();if(!response.ok)throw new Error(json.error||'Не удалось загрузить кабинет');if(json.role==='admin'||json.role==='designer'){router.replace('/admin');return;}setData(json);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить кабинет.')}})()},[router]);
 async function logout(){const supabase=getSupabaseBrowser();await supabase.auth.signOut();router.push('/')}
 if(error)return <main className="account"><header><Link href="/" className="brand">re:project</Link></header><div className="empty"><small>ACCOUNT / ERROR</small><h3>{error}</h3><Link className="dark" href="/login">Войти заново </Link></div></main>;
 if(!data)return <div className="loading">re:project</div>;
 const visuals=data.visualizations||[], requests=data.requests||[], payments=data.payments||[];
 return <main className="account"><header><Link href="/" className="brand">re:project</Link><div>{data.user.email}<button onClick={logout}>Выйти</button></div></header><div className="accountShell"><aside><div className="eyebrow">PRIVATE SPACE</div><h1>Личный<br/>кабинет.</h1>{[['projects','Мои проекты'],['chat','Чаты'],['education','Материалы'],['files','Файлы'],['payments','Оплата']].map(([k,v])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}>{v}<span></span></button>)}<Link className="new" href="/#services">+ Новая задача</Link></aside><section className="dash">
 {tab==='projects'&&<><div className="eyebrow">PROJECTS / {String(requests.length+visuals.length).padStart(2,'0')}</div><h2>Мои проекты</h2>{!requests.length&&!visuals.length?<div className="empty"><small>NO ACTIVE PROJECTS</small><h3>Здесь появится ваш первый проект.</h3><p>Создайте проект, загрузите пространство и продолжайте работу вместе с дизайнером и AI.</p><Link href="/service/visual">Начать проект →</Link></div>:<><div className="accountList">{requests.map((r)=><div className="accountBrief" key={r.id}><small>REQUEST · {r.service_title}</small><h3>{r.service_title}</h3><p>{r.message||'Заявка создана через сайт.'}</p><p className="projectDate">{new Date(r.created_at).toLocaleString('ru-RU')} · статус: {r.status}</p></div>)}</div>{visuals.map(v=><div className="accountProject" key={v.id}><div className="accountProjectImage"><img src={v.image} alt="AI-визуализация"/></div><div className="accountProjectInfo"><small>PROJECT / AI</small><h3>Работа над пространством</h3><p>Стиль: {v.style}</p><p>Здесь можно продолжать дорабатывать пространство вместе с дизайнером.</p><p className="projectDate">{new Date(v.created_at).toLocaleString('ru-RU')}</p><Link className="dark" href="/service/visual">Продолжить работу </Link></div></div>)}</>}</>}
 {tab==='chat'&&<><div className="eyebrow">MESSAGES</div><h2>Чаты</h2><div className="accountChat"><div className="chatIntro"><small>DESIGNER / AI</small><h3>Работаем над пространством вместе.</h3><p>Здесь будет основная коммуникация с дизайнером: вопросы, решения, комментарии и AI-варианты в контексте вашего проекта.</p></div>{data.messages?.length>0&&<div className="chatMessages">{data.messages.map((m:any)=><div className={m.sender_role==='client'?'chatMessage client':'chatMessage'} key={m.id}><small>{m.sender_role==='client'?'ВЫ':'RE:PROJECT'} · {new Date(m.created_at).toLocaleString('ru-RU')}</small><p>{m.body}</p></div>)}</div>}<div className="chatComposer">{requests.length>0&&<select className="chatProjectSelect" value={chatProjectId||requests[0]?.id||''} onChange={e=>setChatProjectId(e.target.value)}><option value="">Выберите проект</option>{requests.map((r:any)=><option key={r.id} value={r.id}>{r.service_title} · {new Date(r.created_at).toLocaleDateString('ru-RU')}</option>)}</select>}<textarea value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="Напишите дизайнеру, что хотите изменить…" rows={5} />{chatError&&<div className="formError">{chatError}</div>}<button className="dark" type="button" disabled={chatSending||!chatText.trim()} onClick={async()=>{try{setChatSending(true);setChatError('');const supabase=getSupabaseBrowser();const{data:auth}=await supabase.auth.getSession();const r=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.session?.access_token||''}`},body:JSON.stringify({body:chatText,requestId:chatProjectId||requests[0]?.id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Не удалось отправить сообщение');setChatText('');setData((d:any)=>({...d,messages:[...(d.messages||[]),j.message]}));}catch(e){setChatError(e instanceof Error?e.message:'Не удалось отправить сообщение')}finally{setChatSending(false)}}}>{chatSending?'Отправляем…':'Отправить сообщение '}</button></div></div></>}
 {tab==='education'&&<><div className="eyebrow">EDUCATION / PURCHASES</div><h2>Мои материалы</h2>{(data.educationAccess||[]).length?<div className="accountList">{data.educationAccess.map((a:any)=><div className="accountBrief" key={a.product_slug}><small>ACCESS · {a.product_slug}</small><h3>{a.product_slug.replaceAll('-',' ')}</h3><p>Доступ активирован {new Date(a.granted_at).toLocaleString('ru-RU')}.</p><div className="materialDownloads">{(getEducationOffer(a.product_slug)?.files||[]).map((f:string)=><DownloadButton key={f} product={a.product_slug} file={f}/>)}</div><Link className="dark" href={`/education/${a.product_slug}`}>Открыть материал </Link></div>)}</div>:<div className="empty"><small>NO PURCHASES</small><h3>Покупок пока нет.</h3><p>После оплаты материалы появятся здесь.</p><Link href="/education">Перейти к материалам </Link></div>}</>}
 {tab==='files'&&<><div className="eyebrow">FILES</div><h2>Файлы</h2><div className="empty"><small>STORAGE</small><h3>Файлы проекта.</h3><p>Сгенерированные AI-визуализации уже хранятся в приватном Supabase Storage и доступны из вашего аккаунта.</p></div></>}
 {tab==='payments'&&<><div className="eyebrow">PAYMENT</div><h2>Оплата</h2>{requests.filter((r:any)=>r.status!=='paid'&&/\d/.test(r.price||'')).map((r:any)=><div className="wallet" key={r.id}><small>{r.service_title}</small><strong>{r.price}</strong><PaymentPanel amount={Number(String(r.price).replace(/\D/g,''))} description={`re:project — ${r.service_title}`} requestId={r.id} onPaid={()=>window.location.reload()}/></div>)}{!requests.some((r:any)=>r.status!=='paid'&&/\d/.test(r.price||''))&&<div className="empty short"><small>К ОПЛАТЕ</small><h3>Неоплаченных заказов нет.</h3></div>}<div className="empty short"><small>TRANSACTIONS / {String(payments.length).padStart(2,'0')}</small>{payments.length?<div>{payments.map((p:any)=><p key={p.id}>{p.amount.toLocaleString('ru-RU')} ₽ · {p.status} · {new Date(p.created_at).toLocaleString('ru-RU')}</p>)}</div>:<h3>История оплат пока пуста.</h3>}</div></>}
 </section></div></main>}
