'use client';
import Header from '@/components/Header';
import Link from 'next/link';
import { services } from '@/lib/services';
import ServiceCard from '@/components/ServiceCard';
import { architectureProjects } from '@/lib/projects';
import HouseVisual from '@/components/HouseVisual';

export default function Home() {
  return <><Header/><main>
    <section className="hero"><div className="eyebrow">ARCHITECTURE / INTERIOR / AI</div><h1>Переосмыслить<br/><em>пространство.</em></h1><p>re:project — авторский сервис архитектора и дизайнера: архитектура, интерьеры и практические инструменты для дизайнеров.</p><div className="heroActions"><Link className="dark" href="/service/visual">Создать визуализацию <span className="arrowIcon"></span></Link><Link className="outline" href="/education">Инструменты для дизайнеров <span className="arrowIcon"></span></Link></div><div className="heroLine"/></section>
    <section id="start" className="selector"><div className="sectionTag">01 / START</div><div><div className="eyebrow">ПЕРВЫЙ ШАГ</div><h2>Что проектируем?</h2><div className="choices"><Link className='choiceButton' href="/brief/apartment"><small>01</small><b>Квартиру</b><span><span className="arrowIcon"></span></span></Link><Link className='choiceButton' href="/brief/house"><small>02</small><b>Дом</b><span><span className="arrowIcon"></span></span></Link></div></div></section>
    <section id="services" className="services"><div className="sectionTag">02 / SERVICES</div><div><div className="sectionHead"><div><div className="eyebrow">RE:PROJECT SERVICES</div><h2>Выберите<br/><em>задачу.</em></h2></div><p>Начните с AI-визуализации или обратитесь к специалисту за консультацией и полноценным проектированием.</p></div><div className="serviceGrid">{services.map((item)=><ServiceCard service={item} key={item.id}/>)}</div></div></section>
    <section id="architecture" className="architecturePreview"><div className="sectionTag">03 / ARCHITECTURE</div><div><div className="sectionHead"><div><div className="eyebrow">READY PROJECTS</div><h2>Архитектура<br/><em>от re:project.</em></h2></div><p>Три типовых проекта частных домов — re:project 1—3. Разные планировочные сценарии, единый подход: от архитектуры и конструктивных решений до чистовой отделки и готового интерьера.</p></div><div className="architectureCards">{architectureProjects.map((project)=><Link href={`/projects/${project.id}`} className="architectureCard" key={project.id}>{project.exterior ? <img className="architectureCardImage" src={project.exterior} alt={`${project.title} — визуализация экстерьера`} /> : <HouseVisual variant={project.accent}/>}<div className="architectureCardInfo"><div><small>{project.number}</small><strong>{project.title}</strong></div><span>{project.area} · {project.floors}</span></div></Link>)}</div><Link className="outline architectureLink" href="/projects">Смотреть все проекты <span className="arrowIcon"></span></Link></div></section>
    <section id="about" className="about"><div className="sectionTag">04 / AUTHOR</div><div className="aboutGrid"><div className="authorPhotoWrap"><img src="/author.jpg" alt="Архитектор-дизайнер" className="authorPhoto"/><div className="authorCaption">АРХИТЕКТОР / ДИЗАЙНЕР<br/>2018 — NOW</div></div><div><div className="eyebrow">АВТОРСКИЙ ПОДХОД</div><h2>Не только<br/><em>визуализация.</em></h2><p className="lead">Архитектор-дизайнер с 2018 года, специализируюсь на проектировании частных домов и разработке дизайн-проектов интерьеров.</p><p>Веду проекты полного цикла: от концепции и рабочей документации до комплектации объекта, взаимодействия с подрядчиками и авторского надзора.</p><p>Имею опыт проектирования домов по разным технологиям, включая каркасное строительство, клеёный брус и керамические блоки Porotherm. Консультирую по реализуемости дизайн-проектов, помогаю адаптировать их под строительство, бюджет и требования заказчика.</p><p>Собственная бригада позволяет контролировать качество работ на всех этапах.</p><div className="authorTeam"><b>Полный цикл</b><span>собственная бригада · команда проектировщиков</span></div></div></div></section>
    <section className="educationPreview"><div className="sectionTag">05 / EDUCATION</div><div className="educationPreviewInner"><div><div className="eyebrow">RE:PROJECT EDUCATION</div><h2>Инструменты<br/><em>для дизайнеров.</em></h2></div><div><p>Готовые кейсы, чеклисты, шаблоны и рабочие системы — без уроков и домашней работы. Купили, получили материалы, применили в своём проекте.</p><Link className="outline" href="/education">Смотреть материалы <span className="arrowIcon"></span></Link></div></div></section>
    <section className="cta"><div className="eyebrow">05 / START</div><h2>Есть фотография?<br/><em>Давайте изменим пространство.</em></h2><Link className="light" href="/service/visual">Начать AI-визуализацию <span className="arrowIcon"></span></Link></section>
  </main><footer><div><b>re:project</b><p>architecture · interior · technology</p></div><div><small>КОНТАКТЫ</small><a href="mailto:hello@reproject.ru">hello@reproject.ru</a><a href="https://t.me/re_project" target="_blank" rel="noreferrer">@re:project</a></div><div><small>ЮРИДИЧЕСКОЕ</small><a href="/legal/contract">Договор оказания услуг</a><a href="/legal">Политика обработки данных</a></div><p className="copy">© 2026 re:project</p></footer></>;
}
